name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  test:
    name: Test on Python 3.7 and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [macOS-10.14, macOS-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          make install
      - name: Test
        run: |
          make ci

  release:
    name: Release
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          make install
      - name: Build
        run: |
          make build
      - name: Publish
        env:
          POETRY_USERNAME: ${{ secrets.PYPI_USERNAME }}
          POETRY_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          poetry publish -u $POETRY_USERNAME -p $POETRY_PASSWORD
